server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: missk72387
      url: jdbc:mysql://localhost:3306/javaweb?useUnicode=true;characterEncoding=UTF-8;GMT%2B8

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted          #指明POJO中的deleted字段作为逻辑删除判断符 #
      logic-delete-value: 1                #删除的数据deleted字段值为1 #
      logic-not-delete-value: 0            #没有删除的数据deleted字段值为0 #

  # 开启MybatisPlus的日志（输出到控制台）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
